document.addEventListener('nexus:ready',()=>{
  const N=window.NexusSidebar;
  function btn(item,custom=false){const b=document.createElement('button');b.className='nexus-icon'+(N.active?.id===item.id?' active':'');b.title=item.name;b.append(N.iconNode(item,custom));b.onclick=()=>N.activate(item,custom);return b;}
  N.renderRail=()=>{N.icons.replaceChildren();N.FEATURES.forEach((x,i)=>{if(i===2){const d=document.createElement('div');d.className='nexus-sep';N.icons.append(d)}N.icons.append(btn(x))});if(N.sites.length){const d=document.createElement('div');d.className='nexus-sep';N.icons.append(d);N.sites.forEach(x=>N.icons.append(btn(x,true)));}};
  N.closeActive=async()=>{if(N.active?.type==='web'||String(N.active?.id||'').startsWith('site-'))await N.destroySite(N.active.id);N.active=null;N.panel.classList.remove('open');N.renderRail();};
  N.activate=async(item,custom=false)=>{N.active=item;N.setHeader(item,custom);N.panel.classList.add('open');N.root.classList.add('rail-visible');N.renderRail();if(item.type==='web'||custom)return N.openSite(item);N.showLocal();N.body.replaceChildren();if(item.id==='launchpad')renderLaunchpad();else if(item.id==='history')renderHistory();else if(item.id==='calculator')renderCalc();else if(item.id==='games')N.renderGames?.();else if(item.id==='settings')N.renderSettings?.();};
  function daily(){const d=new Date();return N.quotes[(d.getDate()+d.getMonth()*31)%N.quotes.length]}
  function renderLaunchpad(){
    const hero=document.createElement('div');hero.className='nexus-hero';const name=N.settings.profileName?`, ${N.settings.profileName}`:'';hero.innerHTML=`<h1>Hello${name}</h1><p>“${daily()}”</p>`;
    const search=document.createElement('form');search.className='nexus-search';search.innerHTML='<input placeholder="Search Google or enter a URL"><button>Go</button>';search.onsubmit=e=>{e.preventDefault();let q=search.querySelector('input').value.trim();if(!q)return;const url=/^https?:\/\//i.test(q)?q:'https://www.google.com/search?q='+encodeURIComponent(q);location.href=url};
    const cards=document.createElement('div');cards.className='nexus-dashboard';const time=document.createElement('div');time.className='nexus-card';const weather=document.createElement('div');weather.className='nexus-card';cards.append(time,weather);
    const tick=()=>{const d=new Date();time.innerHTML=`<b>${d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</b><small>${d.toLocaleDateString([],{weekday:'long',month:'short',day:'numeric'})}</small>`};tick();const t=setInterval(tick,1000);N.cleanup.push(()=>clearInterval(t));
    weather.innerHTML='<b>Weather</b><small>Loading…</small>';N.msg({type:'nexus:weather',location:N.settings.weatherLocation||''}).then(r=>{if(r?.ok)weather.innerHTML=`<b>${r.weather.temp}°F · ${r.weather.condition}</b><small>${r.weather.location||'Current area'}</small>`;else weather.querySelector('small').textContent='Unavailable'});
    const qa=document.createElement('div');qa.className='nexus-quick';[['＋','New tab',()=>N.msg({type:'nexus:new-tab'})],['↻','Reload',()=>N.msg({type:'nexus:reload'})],['🕘','History',()=>N.activate(N.FEATURES[1])],['🧮','Calculator',()=>N.activate(N.FEATURES[3])],['🎮','Games',()=>N.activate(N.FEATURES[4])]].forEach(([i,n,f])=>{const b=document.createElement('button');b.innerHTML=`<b>${i}</b><small>${n}</small>`;b.onclick=f;qa.append(b)});
    const apps=document.createElement('div');apps.className='nexus-appgrid';[...N.FEATURES.filter(x=>x.id!=='launchpad'),...N.sites].forEach(x=>{const b=document.createElement('button');b.append(N.iconNode(x,String(x.id).startsWith('site-')));const s=document.createElement('small');s.textContent=x.name;b.append(s);b.onclick=()=>N.activate(x,String(x.id).startsWith('site-'));apps.append(b)});
    N.body.append(hero,search,cards,qa,apps);
  }
  async function renderHistory(){const input=document.createElement('input');input.className='nexus-wide';input.placeholder='Search history';const list=document.createElement('div');list.className='nexus-list';N.body.append(input,list);const load=async()=>{const r=await N.msg({type:'nexus:history',query:input.value});list.replaceChildren();(r.results||[]).slice(0,60).forEach(x=>{const a=document.createElement('a');a.href=x.url;a.textContent=x.title||x.url;list.append(a)})};input.oninput=load;load();}
  function renderCalc(){N.body.innerHTML='<div class="nexus-calc"><input id="nc" placeholder="2 * (3 + 4)"><button>=</button><output>0</output></div>';const i=N.body.querySelector('input'),o=N.body.querySelector('output');N.body.querySelector('button').onclick=()=>{try{const s=i.value;if(!/^[0-9+\-*/().%\s]+$/.test(s))throw 0;o.textContent=String(Function('return ('+s+')')())}catch{o.textContent='Error'}};}
  N.renderRail();N.activate(N.FEATURES[0]);
});
