document.addEventListener('nexus:ready',()=>{
  const N=window.NexusSidebar;
  N.renderGames=()=>{N.runCleanup();N.body.replaceChildren();const wrap=document.createElement('div');wrap.className='nexus-race-wrap';wrap.innerHTML='<div class="nexus-race-title"><div><b>Apex GP</b><small>3D F1 sprint · 3 laps</small></div><button class="nexus-race-restart">Restart</button></div><canvas class="nexus-race" width="720" height="430" tabindex="0"></canvas><div class="nexus-race-hud"><span data-speed>0 km/h</span><span data-lap>Lap 1/3</span><span data-pos>P 1/6</span><span data-time>0.0s</span></div><div class="nexus-race-controls"><button data-left>◀</button><button data-brake>Brake</button><button data-go>Throttle</button><button data-right>▶</button></div><p class="nexus-game-help">Arrow keys / WASD · Space = DRS boost on straights</p>';N.body.append(wrap);startRace(wrap);};

  function startRace(wrap){
    const canvas=wrap.querySelector('canvas'),ctx=canvas.getContext('2d'),speedEl=wrap.querySelector('[data-speed]'),lapEl=wrap.querySelector('[data-lap]'),posEl=wrap.querySelector('[data-pos]'),timeEl=wrap.querySelector('[data-time]');
    const state={speed:0,x:0,distance:0,lap:1,laps:3,running:true,finished:false,start:performance.now(),last:performance.now(),keys:new Set(),drs:1,shake:0};
    const stats=N.games.race||={best:null,races:0};stats.races++;N.games.race=stats;N.storeSet({nexusGames:N.games});
    const trackLength=12600,maxSpeed=330,drawDistance=3300;
    const ai=[[-.62,277,240],[-.28,293,880],[.22,286,1530],[.58,300,2210],[.02,282,3140]].map(([lane,v,d],i)=>({lane,speed:v,distance:d,total:d,color:['#d33','#e6b800','#1677ff','#111','#2f9d55'][i]}));
    const curveAt=d=>.72*Math.sin(d/1450)+.38*Math.sin(d/530)+.14*Math.sin(d/210);
    const straightAt=d=>Math.abs(curveAt(d))<.34;
    const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
    function roadCenter(rel){let sum=0;const steps=8;for(let i=0;i<steps;i++)sum+=curveAt(state.distance+rel*(i/steps));return sum*70*(rel/drawDistance);}
    function project(rel,lane){const t=clamp(1-rel/drawDistance,0,1),p=Math.pow(t,.72),y=126+p*270,half=18+p*300,center=canvas.width/2+roadCenter(rel);return{x:center+lane*half*.72,y,scale:.18+p*.95,half,center};}
    function carShape(x,y,s,color,player=false){ctx.save();ctx.translate(x,y);if(state.shake&&player)ctx.translate((Math.random()-.5)*state.shake,(Math.random()-.5)*state.shake);ctx.scale(s,s);ctx.fillStyle='#111';ctx.fillRect(-27,-7,9,29);ctx.fillRect(18,-7,9,29);ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(-18,18);ctx.lineTo(-13,-14);ctx.lineTo(-7,-27);ctx.lineTo(7,-27);ctx.lineTo(13,-14);ctx.lineTo(18,18);ctx.closePath();ctx.fill();ctx.fillRect(-28,12,56,7);ctx.fillRect(-19,-19,38,5);ctx.fillStyle=player?'#f2f4f8':'rgba(255,255,255,.8)';ctx.fillRect(-4,-15,8,14);ctx.restore();}
    function drawBackground(){const w=canvas.width,h=canvas.height;const sky=ctx.createLinearGradient(0,0,0,150);sky.addColorStop(0,'#8fb8da');sky.addColorStop(1,'#dbe7ef');ctx.fillStyle=sky;ctx.fillRect(0,0,w,150);ctx.fillStyle='#8ca06b';ctx.fillRect(0,110,w,45);ctx.fillStyle='#65784f';ctx.beginPath();ctx.moveTo(0,130);for(let x=0;x<=w;x+=55)ctx.lineTo(x,112+Math.sin(x*.031)*14+Math.sin(x*.011)*8);ctx.lineTo(w,150);ctx.lineTo(0,150);ctx.fill();}
    function drawRoad(){drawBackground();const slices=52;let prev=null;for(let i=0;i<=slices;i++){const t=i/slices,y=126+Math.pow(t,1.52)*304,half=16+Math.pow(t,1.07)*344,rel=(1-t)*drawDistance,center=canvas.width/2+roadCenter(rel);if(prev){const alt=(Math.floor((state.distance+rel)/120)%2)===0;ctx.fillStyle=alt?'#6d8f4a':'#668845';ctx.fillRect(0,prev.y,canvas.width,y-prev.y+2);ctx.fillStyle=alt?'#e8e8e8':'#c92f2f';poly(prev.center-prev.half-16,prev.y,prev.center-prev.half,prev.y,center-half,y,center-half-20,y);poly(prev.center+prev.half,prev.y,prev.center+prev.half+16,prev.y,center+half+20,y,center+half,y);ctx.fillStyle=alt?'#3b3e42':'#404348';poly(prev.center-prev.half,prev.y,prev.center+prev.half,prev.y,center+half,y,center-half,y);if(i%7===0){ctx.strokeStyle='rgba(255,255,255,.55)';ctx.lineWidth=Math.max(1,t*3);ctx.beginPath();ctx.moveTo(prev.center,prev.y);ctx.lineTo(center,y);ctx.stroke();}}prev={y,half,center};}
      function poly(...p){ctx.beginPath();ctx.moveTo(p[0],p[1]);for(let i=2;i<p.length;i+=2)ctx.lineTo(p[i],p[i+1]);ctx.closePath();ctx.fill()}
    }
    function drawScenery(){for(let rel=500;rel<drawDistance;rel+=520){const p=project(rel,0),side=((Math.floor((state.distance+rel)/520)%2)*2-1),x=p.center+side*(p.half+36*p.scale);ctx.fillStyle='#254c2d';ctx.fillRect(x-3*p.scale,p.y-30*p.scale,6*p.scale,30*p.scale);ctx.beginPath();ctx.arc(x,p.y-34*p.scale,13*p.scale,0,Math.PI*2);ctx.fill();}}
    function drawCars(){const totalPlayer=(state.lap-1)*trackLength+state.distance;for(const a of ai){const rel=((a.distance-state.distance)%trackLength+trackLength)%trackLength;if(rel>70&&rel<drawDistance){const p=project(rel,a.lane);carShape(p.x,p.y-18*p.scale,p.scale*.78,a.color)}}const player=project(0,state.x);carShape(player.x,394,.98,'#e1261c',true);ctx.fillStyle='#111';ctx.font='700 12px system-ui';ctx.textAlign='center';ctx.fillText('NEXUS GP',player.x,421);ctx.textAlign='left';let place=1;for(const a of ai)if(a.total>totalPlayer)place++;posEl.textContent=`P ${place}/6`;}
    function update(dt){if(!state.running)return;const throttle=state.keys.has('ArrowUp')||state.keys.has('KeyW')||state.keys.has('go'),brake=state.keys.has('ArrowDown')||state.keys.has('KeyS')||state.keys.has('brake'),left=state.keys.has('ArrowLeft')||state.keys.has('KeyA')||state.keys.has('left'),right=state.keys.has('ArrowRight')||state.keys.has('KeyD')||state.keys.has('right'),boost=state.keys.has('Space')&&state.drs>0&&straightAt(state.distance);
      if(throttle)state.speed+=82*dt;else state.speed-=35*dt;if(brake)state.speed-=145*dt;if(boost){state.speed+=95*dt;state.drs-=.34*dt}else state.drs=Math.min(1,state.drs+.08*dt);state.speed=clamp(state.speed,0,maxSpeed+(boost?38:0));const steer=(.75+.8*(state.speed/maxSpeed))*dt;if(left)state.x-=steer;if(right)state.x+=steer;state.x=clamp(state.x,-1.12,1.12);if(Math.abs(state.x)>.92)state.speed-=95*dt;
      state.distance+=state.speed*dt*1.72;if(state.distance>=trackLength){state.distance-=trackLength;state.lap++;if(state.lap>state.laps){finish();return}}
      for(const a of ai){a.distance=(a.distance+a.speed*dt*1.58)%trackLength;a.total=(a.total||a.distance)+a.speed*dt*1.58;const rel=((a.distance-state.distance)%trackLength+trackLength)%trackLength;if(rel<120&&Math.abs(state.x-a.lane)<.28){state.speed*=.72;state.shake=8;state.x+=state.x<a.lane?-.08:.08}}state.shake=Math.max(0,state.shake-30*dt);
      speedEl.textContent=`${Math.round(state.speed)} km/h${boost?' · DRS':''}`;lapEl.textContent=`Lap ${Math.min(state.lap,state.laps)}/${state.laps}`;timeEl.textContent=((performance.now()-state.start)/1000).toFixed(1)+'s';}
    function finish(){state.running=false;state.finished=true;const time=(performance.now()-state.start)/1000;if(stats.best==null||time<stats.best)stats.best=time;N.storeSet({nexusGames:N.games});setTimeout(()=>{ctx.fillStyle='rgba(255,255,255,.94)';ctx.fillRect(150,150,420,115);ctx.fillStyle='#111';ctx.textAlign='center';ctx.font='800 28px system-ui';ctx.fillText('FINISH',360,190);ctx.font='600 17px system-ui';ctx.fillText(`${time.toFixed(2)}s · Best ${stats.best.toFixed(2)}s`,360,222);ctx.textAlign='left'},10)}
    function frame(now){const dt=Math.min(.035,(now-state.last)/1000);state.last=now;update(dt);drawRoad();drawScenery();drawCars();if(state.running)state.raf=requestAnimationFrame(frame);}
    function key(e,down){if(!document.contains(canvas))return;const codes=['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyA','KeyS','KeyD','Space'];if(!codes.includes(e.code))return;e.preventDefault();down?state.keys.add(e.code):state.keys.delete(e.code)}
    const kd=e=>key(e,true),ku=e=>key(e,false);document.addEventListener('keydown',kd,true);document.addEventListener('keyup',ku,true);N.cleanup.push(()=>{state.running=false;cancelAnimationFrame(state.raf);document.removeEventListener('keydown',kd,true);document.removeEventListener('keyup',ku,true)});
    [['left','left'],['right','right'],['go','go'],['brake','brake']].forEach(([attr,k])=>{const b=wrap.querySelector(`[data-${attr}]`);const on=e=>{e.preventDefault();state.keys.add(k)},off=e=>{e.preventDefault();state.keys.delete(k)};b.addEventListener('pointerdown',on);b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off);b.addEventListener('pointerleave',off)});
    wrap.querySelector('.nexus-race-restart').onclick=()=>{N.runCleanup();N.renderGames()};canvas.focus();state.raf=requestAnimationFrame(frame);
  }
});
