document.addEventListener('nexus:ready',()=>{
  const N=window.NexusSidebar;
  N.renderGames=()=>{N.body.replaceChildren();const tabs=document.createElement('div');tabs.className='nexus-game-tabs';const host=document.createElement('div');N.body.append(tabs,host);[['dash','Dash Runner'],['ttt','Tic-Tac-Toe']].forEach(([id,n])=>{const b=document.createElement('button');b.textContent=n;b.onclick=()=>id==='dash'?dash(host):ttt(host);tabs.append(b)});dash(host)};
  function save(){N.storeSet({nexusGames:N.games})}
  function dash(host){host.replaceChildren();const stats=N.games.dash||={best:0,runs:0};const c=document.createElement('canvas');c.width=420;c.height=230;c.tabIndex=0;const info=document.createElement('div');info.className='nexus-game-info';info.textContent=`Best ${stats.best} · Runs ${stats.runs}`;host.append(c,info);const x=c.getContext('2d');let y=170,vy=0,score=0,running=false,last=0,spawn=500,obs=[],plat=[];
    function reset(){y=170;vy=0;score=0;spawn=450;obs=[];plat=[];running=true;stats.runs++;save();last=performance.now();requestAnimationFrame(loop)}
    function jump(){if(!running){reset();return}if(y>=169||plat.some(p=>Math.abs((y+24)-p.y)<5&&35+24>p.x&&35<p.x+p.w)){vy=-390}}
    c.onpointerdown=jump;const key=e=>{if((e.code==='Space'||e.code==='ArrowUp')&&document.contains(c)){e.preventDefault();jump()}};document.addEventListener('keydown',key,true);N.cleanup.push(()=>document.removeEventListener('keydown',key,true));
    function addPattern(){const r=Math.random();if(r<.35)obs.push({x:440,y:184,w:22,h:22,t:'spike'});else if(r<.55)obs.push({x:440,y:176,w:28,h:28,t:'saw'});else if(r<.8){plat.push({x:440,y:148,w:90,h:12});if(Math.random()<.5)obs.push({x:500,y:126,w:20,h:22,t:'spike'})}else{obs.push({x:440,y:184,w:20,h:22,t:'spike'},{x:475,y:184,w:20,h:22,t:'spike'});}}
    function loop(now){if(!running)return;const dt=Math.min(.03,(now-last)/1000);last=now;score+=dt*12;spawn-=dt*1000;if(spawn<=0){addPattern();spawn=Math.max(360,760-score*4)+Math.random()*260}vy+=1050*dt;y+=vy*dt;const speed=190+Math.min(120,score*2);for(const a of [...obs,...plat])a.x-=speed*dt;
      let floor=194;for(const p of plat){if(35+24>p.x&&35<p.x+p.w&&vy>=0&&y+24<=p.y+10&&y+24+vy*dt>=p.y){floor=p.y;y=p.y-24;vy=0}}if(y+24>=floor){y=floor-24;vy=0}if(y>230)end();
      for(const o of obs){if(35+21>o.x&&35<o.x+o.w&&y+22>o.y&&y<o.y+o.h){end();return}}draw();obs=obs.filter(o=>o.x>-50);plat=plat.filter(p=>p.x>-120);requestAnimationFrame(loop)}
    function end(){running=false;stats.best=Math.max(stats.best,Math.floor(score));save();info.textContent=`Best ${stats.best} · Last ${Math.floor(score)} · Runs ${stats.runs}`;draw()}
    function draw(){x.clearRect(0,0,420,230);const g=x.createLinearGradient(0,0,420,230);g.addColorStop(0,'#080b19');g.addColorStop(1,'#23104a');x.fillStyle=g;x.fillRect(0,0,420,230);x.strokeStyle='rgba(124,92,255,.22)';for(let i=0;i<12;i++){x.beginPath();x.moveTo(i*40-(score*8%40),0);x.lineTo(i*40-(score*8%40),230);x.stroke()}x.fillStyle='#713cff';x.fillRect(0,194,420,36);for(const p of plat){x.fillStyle='#5630c9';x.fillRect(p.x,p.y,p.w,p.h);x.fillStyle='#a78bfa';x.fillRect(p.x,p.y,p.w,3)}for(const o of obs){if(o.t==='spike'){x.fillStyle='#ff4d9d';x.beginPath();x.moveTo(o.x,o.y+o.h);x.lineTo(o.x+o.w/2,o.y);x.lineTo(o.x+o.w,o.y+o.h);x.fill()}else{x.fillStyle='#ffcc4d';x.beginPath();x.arc(o.x+14,o.y+14,14,0,Math.PI*2);x.fill()}}x.fillStyle='#58e1ff';x.fillRect(35,y,24,24);x.strokeStyle='#fff';x.strokeRect(36,y+1,22,22);x.fillStyle='#fff';x.font='bold 14px system-ui';x.fillText(Math.floor(score),12,22);if(!running){x.fillStyle='rgba(0,0,0,.35)';x.fillRect(0,0,420,230);x.fillStyle='#fff';x.textAlign='center';x.fillText('Click / Space to run & jump',210,110);x.textAlign='left'}}draw();
  }
  function ttt(host){host.replaceChildren();const g=N.games.ttt||={wins:0,losses:0,draws:0,difficulty:'normal'};let board=Array(9).fill('');const info=document.createElement('div');info.className='nexus-game-info';const grid=document.createElement('div');grid.className='nexus-ttt';const sel=document.createElement('select');['easy','normal','hard'].forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;o.selected=g.difficulty===v;sel.append(o)});sel.onchange=()=>{g.difficulty=sel.value;save()};host.append(sel,info,grid);
    const wins=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]],win=p=>wins.some(a=>a.every(i=>board[i]===p));function paint(msg='Your turn'){info.textContent=`${msg} · W ${g.wins} L ${g.losses} D ${g.draws}`;grid.replaceChildren();board.forEach((v,i)=>{const b=document.createElement('button');b.textContent=v;b.disabled=!!v;b.onclick=()=>play(i);grid.append(b)})}
    function finish(){if(win('X')){g.wins++;save();paint('You win!');return true}if(win('O')){g.losses++;save();paint('Bot wins');return true}if(board.every(Boolean)){g.draws++;save();paint('Draw');return true}return false}
    function bot(){const empty=board.map((v,i)=>v?'':i).filter(v=>v!=='');let pick;if(g.difficulty==='hard'||(g.difficulty==='normal'&&Math.random()>.28)){pick=empty.find(i=>{board[i]='O';const w=win('O');board[i]='';return w});if(pick==null)pick=empty.find(i=>{board[i]='X';const w=win('X');board[i]='';return w})}if(pick==null)pick=empty[Math.floor(Math.random()*empty.length)];if(pick!=null)board[pick]='O'}
    function play(i){board[i]='X';if(finish())return;bot();finish()||paint()}paint();
  }
});
