document.addEventListener('nexus:ready',()=>{
  const N=window.NexusSidebar;
  N.destroySite=async id=>{const s=N.sessions.get(id);if(!s)return;try{s.iframe.src='about:blank';s.frame.remove();}catch{}N.sessions.delete(id);if(!N.sessions.size)await N.msg({type:'nexus:frame-disable'});};
  N.showLocal=()=>{N.body.hidden=false;N.sessionsHost.classList.remove('visible');for(const s of N.sessions.values())s.frame.classList.remove('active');};
  N.showSite=s=>{N.body.hidden=true;N.sessionsHost.classList.add('visible');for(const x of N.sessions.values())x.frame.classList.toggle('active',x===s);};
  N.openSite=async item=>{let session=N.sessions.get(item.id);if(!session){const ok=await N.msg({type:'nexus:frame-enable'});if(!ok?.ok){N.body.innerHTML=`<div class="nexus-empty">Could not enable site frame.<br>${ok?.error||''}</div>`;return;}if(N.settings.cookieSync)await N.msg({type:'nexus:cookie-allow',url:item.url});const frame=document.createElement('div');frame.className='nexus-session';const bar=document.createElement('div');bar.className='nexus-sitebar';const host=document.createElement('span');host.textContent=new URL(item.url).hostname;const reload=document.createElement('button');reload.textContent='↻';reload.title='Reload site';const close=document.createElement('button');close.textContent='✕';close.title='End live session';const iframe=document.createElement('iframe');iframe.src=item.url;iframe.name='nexus:'+item.id;iframe.allow='autoplay; clipboard-read; clipboard-write; encrypted-media; fullscreen; picture-in-picture';iframe.referrerPolicy='strict-origin-when-cross-origin';reload.onclick=()=>{try{iframe.src=iframe.src}catch{}};close.onclick=async()=>{await N.destroySite(item.id);N.closePanelSoft();};bar.append(host,reload,close);frame.append(bar,iframe);N.sessionsHost.append(frame);session={frame,iframe,item};N.sessions.set(item.id,session);}N.showSite(session);};
  N.addSite=async(name,url)=>{url=String(url||'').trim();if(!/^https?:\/\//i.test(url))url='https://'+url;try{url=new URL(url).href}catch{return false}const item={id:'site-'+crypto.randomUUID(),name:name.trim()||new URL(url).hostname,url,type:'web'};N.sites.push(item);N.settings.railLayout=N.normalizeLayout();await N.storeSet({nexusSites:N.sites,nexusSettings:N.settings});N.renderRail();return true;};
  N.removeSite=async id=>{await N.destroySite(id);N.sites=N.sites.filter(x=>x.id!==id);N.settings.railLayout=(N.settings.railLayout||[]).filter(x=>x!==id);N.settings.hiddenIcons=(N.settings.hiddenIcons||[]).filter(x=>x!==id);await N.storeSet({nexusSites:N.sites,nexusSettings:N.settings});N.renderRail();};
});
